# Generated by Django 3.1.2 on 2024-06-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0002_chat_messagemodel_eventsmodels_filemodels_groupsmodel_messeger_user_subgroupsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messagemodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groupmessage', to='app_messager.groupsmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_messagemodel',
            name='subgroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subgroup', to='app_messager.subgroupsmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventsmodels',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_messager.groupsmodel'),
            preserve_default=False,
        ),
    ]
