# Generated by Django 3.1.2 on 2024-04-10 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_messager', '0002_alter_messages_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Join', 'join'), ('Left', 'left')], max_length=10)),
                ('description', models.CharField(editable=False, help_text='A description of the event that occurred', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(max_length=50, upload_to='files/%Y/%m/%d/', verbose_name='File path name')),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=30)),
                ('title_order', models.CharField(max_length=50)),
                ('hide', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Messeger_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Author'), ('NA', 'NoAuthor')], max_length=10, unique=True)),
                ('sub_status', models.CharField(choices=[('s', 'Seller'), ('b', 'Buyer')], max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AddField(
            model_name='groupsmodel',
            name='members',
            field=models.ManyToManyField(to='app_messager.Messeger_User'),
        ),
        migrations.AddField(
            model_name='eventsmodels',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_messager.groupsmodel'),
        ),
        migrations.AddField(
            model_name='eventsmodels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_messager.messeger_user'),
        ),
        migrations.AddField(
            model_name='chat_messagemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_messager.messeger_user'),
        ),
        migrations.AddField(
            model_name='chat_messagemodel',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_of_chat', to='app_messager.filemodels'),
        ),
        migrations.AddField(
            model_name='chat_messagemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_messager.groupsmodel'),
        ),
    ]
