# Generated by Django 3.1.2 on 2024-04-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0003_auto_20240410_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodels',
            name='group',
        ),
        migrations.RemoveField(
            model_name='eventsmodels',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupsmodel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='messeger_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat_MessageModel',
        ),
        migrations.DeleteModel(
            name='EventsModels',
        ),
        migrations.DeleteModel(
            name='FileModels',
        ),
        migrations.DeleteModel(
            name='GroupsModel',
        ),
        migrations.DeleteModel(
            name='Messeger_User',
        ),
    ]
