# Generated by Django 3.1.2 on 2024-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0005_chat_messagemodel_eventsmodels_filemodels_groupsmodel_messeger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messeger_user',
            name='status',
            field=models.CharField(choices=[('A', 'Author'), ('NA', 'NoAuthor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='messeger_user',
            name='sub_status',
            field=models.CharField(choices=[('s', 'Seller'), ('b', 'Buyer')], max_length=10),
        ),
    ]
