# Generated by Django 3.1.2 on 2024-04-10 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0006_auto_20240410_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='groupsmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
