# Generated by Django 3.1.2 on 2024-04-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0007_auto_20240411_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_messagemodel',
            name='group',
        ),
    ]
