# Generated by Django 3.1.2 on 2024-04-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0008_remove_chat_messagemodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messagemodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_messager.groupsmodel'),
            preserve_default=False,
        ),
    ]
