# Generated by Django 3.1.2 on 2024-04-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0009_chat_messagemodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodels',
            name='link',
            field=models.FileField(max_length=50, null=True, upload_to='files/%Y/%m/%d/', verbose_name='File path name'),
        ),
    ]
