# Generated by Django 3.1.2 on 2024-04-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0010_auto_20240411_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodels',
            name='link',
            field=models.FileField(max_length=50, upload_to='files/%Y/%m/%d/', verbose_name='File path name'),
        ),
    ]
