# Generated by Django 3.1.2 on 2024-04-11 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0011_auto_20240411_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_of_chat', to='app_messager.filemodels'),
        ),
    ]
