# Generated by Django 3.1.2 on 2024-04-11 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0024_auto_20240411_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autormessage', to='app_messager.messeger_user'),
        ),
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmessage', to='app_messager.groupsmodel'),
        ),
    ]
