# Generated by Django 3.1.2 on 2024-04-11 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0025_auto_20240411_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
