# Generated by Django 3.1.2 on 2024-04-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0026_auto_20240411_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmodel',
            name='members',
            field=models.ManyToManyField(related_name='members_users', to='app_messager.Messeger_User'),
        ),
    ]
