# Generated by Django 3.1.2 on 2024-04-14 08:01

import app_messager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0027_auto_20240412_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodels',
            name='link',
            field=models.FileField(max_length=50, upload_to=app_messager.models.get_timestamp_path, verbose_name='File path name'),
        ),
    ]
