# Generated by Django 3.1.2 on 2024-04-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0028_auto_20240414_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodels',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
