# Generated by Django 3.1.2 on 2024-04-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0029_auto_20240414_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodels',
            name='link',
        ),
        migrations.AddField(
            model_name='filemodels',
            name='limk',
            field=models.CharField(default=0, max_length=100, verbose_name='File path name'),
            preserve_default=False,
        ),
    ]
