# Generated by Django 3.1.2 on 2024-04-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0030_auto_20240415_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodels',
            name='limk',
        ),
        migrations.AddField(
            model_name='filemodels',
            name='link',
            field=models.FileField(default=0, max_length=50, upload_to='files/%Y/%m/%d/', verbose_name='File path name'),
            preserve_default=False,
        ),
    ]
