# Generated by Django 3.1.2 on 2024-04-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0032_auto_20240415_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_of_chat', to='app_messager.filemodels'),
        ),
    ]
