# Generated by Django 3.1.2 on 2024-04-30 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0033_auto_20240428_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroupsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
