# Generated by Django 3.1.2 on 2024-04-30 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0035_auto_20240430_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messagemodel',
            name='subgroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_messager.subgroupsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmessage', to='app_messager.groupsmodel'),
        ),
    ]
