# Generated by Django 3.1.2 on 2024-04-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0037_remove_chat_messagemodel_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messagemodel',
            name='subgroup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_messager.subgroupsmodel'),
            preserve_default=False,
        ),
    ]
