# Generated by Django 3.1.2 on 2024-04-30 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0038_chat_messagemodel_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroupsmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
