# Generated by Django 3.1.2 on 2024-04-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0039_auto_20240430_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_message', to='app_messager.subgroupsmodel'),
        ),
    ]
