# Generated by Django 3.1.2 on 2024-05-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0040_auto_20240430_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filechat', to='app_messager.filemodels'),
        ),
        migrations.AlterField(
            model_name='chat_messagemodel',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup', to='app_messager.subgroupsmodel'),
        ),
    ]
