# Generated by Django 3.1.2 on 2024-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0041_auto_20240502_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
