# Generated by Django 3.1.2 on 2024-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0042_auto_20240607_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
