# Generated by Django 3.1.2 on 2024-06-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0043_auto_20240607_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsmodel',
            name='members',
        ),
    ]
