# Generated by Django 3.1.2 on 2024-06-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0044_remove_groupsmodel_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsmodel',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='groupsmodel',
            name='title_order',
        ),
    ]
