# Generated by Django 3.1.2 on 2024-06-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messager', '0045_auto_20240609_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_messagemodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='eventsmodels',
            name='group',
        ),
        migrations.DeleteModel(
            name='GroupsModel',
        ),
    ]
