name: messager
on: [push, pull_request]
permissions:
  checks: write
  contents: write
  pages: write
  id-token: write
  deployments: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        node-version: [18.x]


    steps:
      # действие проверяет содержимое хранилища, в котором
      # размещен вызывающий рабочий процесс, а не вызываемый рабочий процесс.
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy
        env:
          DJANGO_SETTINGS_MODULE: 'config.settings'
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          python manage.py collectstatic --no-input
          python manage.py migrate
          gunicorn config.wsgi:application --workers 3 --bind 0.0.0.0:8000
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
      #   run: cd src/app/frontend && yarn run build:dev
      - name: Install dependencies
        run: yarn install

      - name: Build-Django
        run: python manage.py collectstatic --noinput
        
      - name: Build-All
        run: yarn run build:dev

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

